apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e1h6lamsc-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e1h6lamsc-nodejs 
  name: e1h6lamsc-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: e1h6lamsc-nodejs 
